services:
  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: xml_processor_development

  worker:
    image: xml_processor_app
    build: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://root:root@db:5432/xml_processor_development

  web:
    image: xml_processor_app
    build: .
    command: bundle exec rails s -b 0.0.0.0
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://root:root@db:5432/xml_processor_development
    ports:
      - "3000:3000"
